services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - ai-resume-builder

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - ai-resume-builder

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ai-resume-builder

networks:
  ai-resume-builder:

volumes:
  mongo-data: